[ENGPROD-6507] filter secrets and licenses based on rego policy
datarobot/trivy pull request #4
Opened 2023-12-14 08:41 UTC by kristyko

## Description

Filter out Secrets and Licenses based on repo ignore policy just like Misconfigurations and Vulnerabilities. 

## Related issues
- Close #XXX

## Related PRs
- [ ] #XXX
- [ ] #YYY

Remove this section if you don't have related PRs.

## Checklist
- [ ] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [ ] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

2023-12-14 18:16 UTC, carsongee requested changes

2023-12-14 18:16 UTC, carsongee commented on pkg/result/filter.go
> +	policyFile string) ([]types.DetectedVulnerability, []types.DetectedMisconfiguration, int, []ftypes.SecretFinding, []types.DetectedLicense, error) {
I think you'll probably want to move these to before the `int` return. Or at least it makes the most logical sense to me that we should return the count of ignored things right before the error

2023-12-14 18:16 UTC, carsongee commented on pkg/result/filter_test.go
> +                                },
Some classic tabs vs. spaces indent problems here

2023-12-14 18:26 UTC, carsongee commented on pkg/result/filter.go
> +	return filteredVulns, filteredMisconfs, ignoredMisconfs, filteredSecrets, filteredLics, nil
So, maybe I'm wrong. It seems really weird that we're using a blind int to "only" return the count of ignored misconfigurations. Probably a follow-up change, but it seems like it would be useful to make a struct with counts of all the ignores

2023-12-14 18:26 UTC, carsongee commented on pkg/result/filter.go
> +	policyFile string) ([]types.DetectedVulnerability, []types.DetectedMisconfiguration, int, []ftypes.SecretFinding, []types.DetectedLicense, error) {
I retract this...it is not what I thought it was 😢

2023-12-14 21:31 UTC, kristyko commented on pkg/result/filter.go
> +	return filteredVulns, filteredMisconfs, ignoredMisconfs, filteredSecrets, filteredLics, nil
@carsongee I just pushed a commit with a fix for the indentation issue. Should I open a follow-up ticket for the structure for ignores?

2023-12-21 18:50 UTC, carsongee commented on pkg/result/filter.go
> +	return filteredVulns, filteredMisconfs, ignoredMisconfs, filteredSecrets, filteredLics, nil
Let's start a "discussion" per their procedures and see if it is of interest for them

2023-12-21 18:51 UTC, carsongee approved these changes
Sorry for the delay. Please also open a PR to their repository with this change, and let's build and push this to our dockerhub registry. Notebooks and Buzok are our first stops to using this new functionality. Thank you for picking this up!

2023-12-27 16:55 UTC, merged